DROP TABLE  IF EXISTS Memes CASCADE;


CREATE TABLE Memes (
	groupId BIGINT NOT NULL,
	postId BIGINT NOT NULL,
	timestamp BIGINT NOT NULL,
	text TEXT NOT NULL,
	photoPaths TEXT NOT NULL,
	PRIMARY KEY (groupId, postId)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT;
