# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import analyzerText_pb2 as analyzerText__pb2


class AnalyzerTextStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.AnalyzeText = channel.unary_unary(
        '/AnalyzerText/AnalyzeText',
        request_serializer=analyzerText__pb2.AnalyzeTextRequest.SerializeToString,
        response_deserializer=analyzerText__pb2.AnalyzeTextResponse.FromString,
        )


class AnalyzerTextServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def AnalyzeText(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_AnalyzerTextServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'AnalyzeText': grpc.unary_unary_rpc_method_handler(
          servicer.AnalyzeText,
          request_deserializer=analyzerText__pb2.AnalyzeTextRequest.FromString,
          response_serializer=analyzerText__pb2.AnalyzeTextResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'AnalyzerText', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
